# ***Task 1:- Data Preparation***

#### ***Import Libraries***

In [1]:
import numpy as np
import pandas as pd

#### ***Reading The Dataset***

In [2]:
df = pd.read_csv('smartphones_uncleaned.csv')

#### ***Check The Shape (Rows And Columns) Of The Dataset***

In [3]:
df.shape

(2928, 14)

#### ***Check The First 5 information Of The Dataset***

In [4]:
df.head()

,model_name,price,expert_rating,user_rating,processor,rear_cameras,front_cameras,display,ram_internal_memory,battery,operating_system,additional_features,review,review_link
0,vivo V40,"34,999",NaN,NaN,Snapdragon 7 Gen 3 Octa core,50+50 MP Rear Camera,50 MP Front Camera,6.78″ (17.22 cm) 120Hz AMOLED Display,8 GB RAM | 128 GB Storage,5500 mAh | 80W Fast Charging,Android v14 OS,5G | Fingerprint Sensor,NaN,NaN
1,OPPO K12x,"12,999",NaN,NaN,MediaTek Dimensity 6300 Octa core,32+2 MP Rear Camera,8 MP Front Camera,6.67″ (16.94 cm) 120Hz LCD Display,6 GB RAM | 128 GB Storage,5100 mAh | 45W Fast Charging,Android v14 OS,5G | Fingerprint Sensor,NaN,NaN
2,vivo V40 Pro,"49,999",8.2,NaN,MediaTek Dimensity 9200 Plus Octa core,50+50+50 MP Rear Camera,50 MP Front Camera,6.78″ (17.22 cm) 120Hz AMOLED Display,8 GB RAM | 256 GB Storage,5500 mAh | 80W Fast Charging,Android v14 OS,5G | Fingerprint Sensor,"The Vivo V40 Pro shines with its cameras, perf...",https://www.mysmartprice.com/gear/mobiles/mobi...
3,Motorola Edge 50 Fusion,"24,879",8.1,4.5 ★\n16.9K Ratings,Snapdragon 7s Gen 2 Octa core,50+13 MP Rear Camera,32 MP Front Camera,6.67″ (16.94 cm) 144Hz P-OLED Display,8 GB RAM | 128 GB Storage,5000 mAh | 68W Fast Charging,Android v14 OS,5G | NFC | Fingerprint Sensor,Moto Edge 50 Fusion has a premium design and s...,https://www.mysmartprice.com/gear/mobiles/mobi...
4,Samsung Galaxy M35 5G,"19,999",NaN,4.3 ★\n383 Ratings,Samsung Exynos 1380 Octa core,50+8+2 MP Rear Camera,13 MP Front Camera,6.6″ (16.76 cm) 120Hz Super AMOLED Display,6 GB RAM | 128 GB Storage,6000 mAh | 25W Fast Charging,Android v14 OS,5G | NFC | Fingerprint Sensor,NaN,NaN

#### ***Check The Information Of Dataset***

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2928 entries, 0 to 2927
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_name           2928 non-null   object
 1   price                2928 non-null   object
 2   expert_rating        1827 non-null   float64
 3   user_rating          2832 non-null   object
 4   processor            2888 non-null   object
 5   rear_cameras         2928 non-null   object
 6   front_cameras        2895 non-null   object
 7   display              2928 non-null   object
 8   ram_internal_memory  2926 non-null   object
 9   battery              2928 non-null   object
 10  operating_system     2919 non-null   object
 11  additional_features  2312 non-null   object
 12  review               1419 non-null   object
 13  review_link          1419 non-null   object
dtypes: float64(1), object(13)
memory usage: 320.4+ KB

#### ***Check missing values***

In [6]:
df.isnull().sum()

model_name                0
price                     0
expert_rating          1101
user_rating              96
processor                40
rear_cameras              0
front_cameras            33
display                   0
ram_internal_memory       2
battery                   0
operating_system          9
additional_features     616
review                 1509
review_link            1509
dtype: int64

#### ***Check duplicate rows***

In [7]:
df.duplicated().sum()

np.int64(672)

#### ***Remove duplicate rows***

In [8]:
df = df.drop_duplicates()

In [9]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (2256, 14)

#### ***Handle missing values***

In [10]:
numric_cols = df.select_dtypes(include = np.number).columns
categorical_cols = df.select_dtypes(include = 'object').columns

#### ***Fill numerical missing values with median***

In [11]:
for column in numric_cols:
    df[column] = df[column].fillna(df[column].median())

#### ***Fill categorical missing values with mode***

In [12]:
for column in categorical_cols:
    if df[column].isnull().sum() > 0:
        df[column] = df[column].fillna(df[column].mode()[0])

#### ***Check missing values again***

In [13]:
print("Missing values after handling:")
print(df.isnull().sum().sum())

Missing values after handling:
0

#### ***Check unique values in categorical columns***

In [14]:
for column in categorical_cols:
    print(f'\n{column}:')
    print(df[column].value_counts().head(10))

model_name:
model_name
vivo V40                    1
HTC Desire 620G             1
I Kall Z19 Prime            1
vivo Y17s 128GB             1
Nokia C32 6GB RAM           1
realme Narzo N53 8GB RAM    1
vivo V7 Plus                1
Xiaomi Mi Max               1
Nokia Asha 210              1
Lava Blaze 2 Pro            1
Name: count, dtype: int64

price:
price
9,999     59
14,999    49
10,999    38
8,999     38
11,999    37
7,999     37
6,999     32
5,999     28
13,999    26
16,999    26
Name: count, dtype: int64

user_rating:
user_rating
4.5 ★\n1.3L Ratings     80
4.2 ★\n1.1L Ratings      8
4.2 ★\n1L Ratings        6
4.4 ★\n19.4K Ratings     6
4.3 ★\n1.4L Ratings      6
4.4 ★\n1.3L Ratings      5
4.3 ★\n1L Ratings        5
4.4 ★\n1.1L Ratings      5
4.3 ★\n1.8L Ratings      5
4.3 ★\n1.3L Ratings      5
Name: count, dtype: int64

processor:
processor
Unisoc Octa core                    129
MediaTek                             83
MediaTek Quad core                   79
MediaTek Tru-Octa Core               70
MediaTek Helio G85 Octa core         51
Samsung Exynos 9 Octa Octa core      47
Snapdragon 695 Octa core             42
Snapdragon 680 Octa core             37
MediaTek Helio P22 Tru-Octa Core     33
MediaTek Octa core                   33
Name: count, dtype: int64

rear_cameras:
rear_cameras
13 MP Rear Camera        257
8 MP Rear Camera         217
50+2 MP Rear Camera      115
5 MP Rear Camera         109
13+2 MP Rear Camera       84
50+8+2 MP Rear Camera     81
64+8+2 MP Rear Camera     67
16 MP Rear Camera         57
50+2+2 MP Rear Camera     53
12+12 MP Rear Camera      48
Name: count, dtype: int64

front_cameras:
front_cameras
8 MP Front Camera      501
16 MP Front Camera     461
5 MP Front Camera      439
32 MP Front Camera     197
2 MP Front Camera      110
13 MP Front Camera     106
12 MP Front Camera      65
0.3 MP Front Camera     62
20 MP Front Camera      55
50 MP Front Camera      49
Name: count, dtype: int64

display:
display
5.0″ (12.7 cm) IPS LCD Display           161
5.5″ (13.97 cm) IPS LCD Display          124
6.67″ (16.94 cm) 120Hz AMOLED Display     77
6.78″ (17.22 cm) 120Hz AMOLED Display     51
6.6″ (16.76 cm) 90Hz IPS LCD Display      40
6.5″ (16.51 cm) 90Hz IPS LCD Display      39
6.5″ (16.51 cm) 60Hz IPS LCD Display      39
6.7″ (17.02 cm) 120Hz AMOLED Display      37
4.7″ (11.94 cm) IPS LCD Display           32
4.5″ (11.43 cm) IPS LCD Display           31
Name: count, dtype: int64

ram_internal_memory:
ram_internal_memory
8 GB RAM | 128 GB Storage     318
4 GB RAM | 64 GB Storage      292
6 GB RAM | 128 GB Storage     271
3 GB RAM | 32 GB Storage      172
8 GB RAM | 256 GB Storage     158
2 GB RAM | 16 GB Storage      141
12 GB RAM | 256 GB Storage    132
1 GB RAM | 8 GB Storage       128
4 GB RAM | 128 GB Storage     119
6 GB RAM | 64 GB Storage       66
Name: count, dtype: int64

battery:
battery
5000 mAh | 18W Fast Charging    145
5000 mAh | 33W Fast Charging    121
5000 mAh | 10W                  119
3000 mAh                         94
4000 mAh                         68
5000 mAh                         57
5000 mAh | 15W Fast Charging     50
5000 mAh | 67W Fast Charging     49
5000 mAh | 45W Fast Charging     42
5000 mAh | 25W Fast Charging     40
Name: count, dtype: int64

operating_system:
operating_system
Android v11 OS       303
Android v13 OS       290
Android v12 OS       238
Android v10 OS       211
Android v14 OS       210
Android v9.0 OS      173
Android v6.0 OS      111
Android v5.1 OS       96
Android v8.1 OS       79
Android v4.4.2 OS     64
Name: count, dtype: int64

additional_features:
additional_features
Fingerprint Sensor               1239
5G | Fingerprint Sensor           340
5G | NFC | Fingerprint Sensor     331
NFC | Fingerprint Sensor          234
NFC                                68
5G | NFC                           44
Name: count, dtype: int64

review:
review
....Read Full Review                                                                                                                                                                                                                                                             1197
The Realme 10 Pro+ has focused on the display factor and introduced the Dimensity 1080 SoC to this price segment. The device runs well in our day-to-day usage, but we noticed a disparity in the refresh rate in certain apps. On the other hand, the cam...Read Full Review       3
Xiaomi Redmi 9 Prime offers Full HD+ resolution for under Rs 10,000 with Corning Gorilla Glass 3 protection. It runs on MIUI version built over Android 10 version out of box and packs a competent set of hardware for decent performance. The phone also...Read Full Review       2
The Realme 6i is a budget offering from the brand and gives value for money features. However, there have been compromises when it comes to design and storage. But it gets a Helio G90T, which is great at this price range. Still, the phone is the go-t...Read Full Review       2
The Realme Narzo 50A Prime feels like a mixed bag for us. Besides the design, display and good battery life, the phone seems average. It appears to be lost in a crowded 5G market now....Read Full Review                                                                          2
The POCO X6 is a great smartphone that offers a good mix of a capable display, lag-free performance, and fast charging battery. The phone also brings segment-leading features such as the new Snapdragon chipset, OIS support, and more. Overall, if you ...Read Full Review       2
The Samsung Galaxy M21 128GB version offers a massive 6000mAh battery that offers great battery life for all your requirements. Samsung bundles 15W charger with device, but you have various options to buy phones with 30W fast charging at this price r...Read Full Review       2
The Nokia C22 is a budget smartphone with a good balance of features and performance. It has a large 6.5-inch HD+ display, a long-lasting 5000mAh battery, and a capable 13MP dual-camera system. However, it is powered by an entry-level Unisoc SC9863A ...Read Full Review       1
The Xiaomi Redmi A2 2023 4GB RAM smartphone offers a budget-friendly option with its MediaTek Helio G36 chipset, 6.52-inch IPS LCD display, and dual rear camera setup. The device provides smooth performance, ample storage, and long battery life. It's...Read Full Review       1
The Samsung Galaxy Z Fold 5 is a premium smartphone from Samsung which boasts an AMOLED display with a 120Hz refresh rate. The device uses a Snapdragon 8 Gen 2 SoC which handles the multitasking with ease. The smartphone is thinner and lighter than t...Read Full Review       1
Name: count, dtype: int64

review_link:
review_link
https://www.mysmartprice.com/gear/mobiles/mobiles-reviews/realme-10-pro-plus-review/                                          1189
https://www.mysmartprice.com/gear/mobiles/mobiles-reviews/realme-narzo-50a-prime-review/                                         2
https://www.mysmartprice.com/gear/mobiles/mobiles-reviews/poco-x6-review-x-traordinary-performance-at-an-affordable-price/       2
https://www.mysmartprice.com/mobile/xiaomi-redmi-note-6-pro-msp15096#scrollTo=expert-reviews                                     1
https://www.mysmartprice.com/mobile/xiaomi-mi-mix-2-msp12249#scrollTo=expert-reviews                                             1
https://www.mysmartprice.com/gear/mobiles/mobiles-reviews/infinix-smart-6-hd-review-the-most-affordable-smartphone/              1
https://www.mysmartprice.com/mobile/realme-gt-neo-3t-5g-8gb-ram-msp22696#scrollTo=expert-reviews                                 1
https://www.mysmartprice.com/mobile/vivo-y16-64gb-msp22730#scrollTo=expert-reviews                                               1
https://www.mysmartprice.com/mobile/infinix-hot-20-5g-128gb-msp23080#scrollTo=expert-reviews                                     1
https://www.mysmartprice.com/mobile/samsung-galaxy-s23-ultra-5g-1tb-msp23122#scrollTo=expert-reviews                             1
Name: count, dtype: int64

#### ***Check numerical summary***

In [15]:
df.describe()

       expert_rating
count    2256.000000
mean        7.799911
std         0.474213
min         3.500000
25%         7.800000
50%         7.800000
75%         8.000000
max         9.500000

#### ***Check final duplicates***

In [16]:
print("\nDuplicates after cleaning:", df.duplicated().sum())

Duplicates after cleaning: 0

#### ***Final dataset information***

In [17]:
print("Final Dataset Shape:", df.shape)
print("Final Missing Values:", df.isnull().sum().sum())

Final Dataset Shape: (2256, 14)
Final Missing Values: 0

#### ***Save prepared dataset***

In [18]:
df.to_csv("smartphones_prepared.csv", index=False)

In [19]:
print("\nData preparation completed successfully!")

Data preparation completed successfully!